config/routes.rb
Rails.application.routes.draw do
  devise_for :users
devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :jobs
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		@jobs=Job.all.order("created_at DESC")
	end
	
	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%=simple_form_for(@job,html: {class:'form-horizontal'}) do |f| %>
  <%= f.input :title, label: "Job Title", input_html: { class: "form-control" } %>
  <%= f.input :description, label: "Job Description", input_html: { class: "form-control" } %>
  <%= f.input :company, label: "Your Company", input_html: { class: "form-control" } %>
  <%= f.input :url, label: "Link to Job", input_html: { class: "form-control" } %>
  <br/>
  <%= f.button :submit %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<%= render 'form' %>
<%= link_to "Back", root_path,class: "btn btn-sm btn-default" %>

app/views/jobs/index.html.erb
<div id="jobs">
  <% @jobs.each do |job| %>
    <div class="job">
      <h2>
        <%= link_to job.title, job %>
      </h2>
      <p>
        <%= job.company %>
      </p>
    </div>
  <% end %>
</div>
<% if user_signed_in? && current_user.admin %>
<%= link_to "New Job",new_job_path,class: "btn btn-sm btn-default" %>
<%end%>

app/views/jobs/new.html.erb
<h1>New Job</h1>
<%= render 'form' %>
<%= link_to "Back", root_path,class: "btn btn-sm btn-default" %>

app/views/jobs/show.html.erb
<div id="jobs">
<div class="job">
<h2><%=@job.title%></h2>
<p><%@job.description%></p>
<% if !current_user.admin? %>
<%= link_to "Apply for Job", job_path(@job),method: :save,data: { confirm: "Applied succesfully" }, class: "btn btn-sm btn-default"%>
<%end%>
</div>
<div id="links">
<%= link_to "Back", root_path, class: "btn btn-sm btn-default"%>
<% if current_user.admin? %>
<%= link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default"%>
<%= link_to "Delete",job_path(@job),method: :Delete, data: { confirm: "Are you sure?" },class: "btn btn-sm btn-default"%>
<%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>ZenHr</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
    <%= link_to "ZenHr", root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav"></ul>
      <% if user_signed_in? && !current_user.admin%>
      <%= link_to "Logout",destroy_user_session_path, class: "navbar-text navbar-right navbar-link" %>
      <% elsif user_signed_in? && current_user.admin%>
      <%= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link" %>
      <%= link_to "Logout",destroy_user_session_path, class: "navbar-text navbar-right navbar-link" %>
      <% else%>
      <%= link_to "Sign In", new_user_session_path, class: "navbar-text navbar-right navbar-link" %>
      <%= link_to "Sing Up", new_user_registration_path, class: "navbar-text navbar-right navbar-link" %>
    <%end%>
      </div>
  </nav>
  <div>
  <% if notice%> <p class="notice"><%= notice %></p> <%end%>
  <% if alert%> <p class="alert"><%= alert %></p><%end%>
  <div>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %>
    </div>
  </div>
</body>
</html>